export const ALLERGENES = [
  { id: 'gluten', label: 'Céréales/Gluten', emoji: '🌾', description: 'Blé, seigle, orge, avoine, épeautre, kamut' },
  { id: 'crustaces', label: 'Crustacés', emoji: '🦞', description: 'Et produits à base de crustacés' },
  { id: 'oeufs', label: 'Œufs', emoji: '🥚', description: 'Et produits à base d\'œufs' },
  { id: 'poissons', label: 'Poissons', emoji: '🐟', description: 'Et produits à base de poissons' },
  { id: 'arachides', label: 'Arachides', emoji: '🥜', description: 'Et produits à base d\'arachides' },
  { id: 'soja', label: 'Soja', emoji: '🫘', description: 'Et produits à base de soja' },
  { id: 'lait', label: 'Lait', emoji: '🥛', description: 'Y compris lactose' },
  { id: 'fruits_a_coque', label: 'Fruits à coque', emoji: '🌰', description: 'Amandes, noisettes, noix, cajou, pécan, macadamia, pistaches' },
  { id: 'celeri', label: 'Céleri', emoji: '🥬', description: 'Et produits à base de céleri' },
  { id: 'moutarde', label: 'Moutarde', emoji: '🌿', description: 'Et produits à base de moutarde' },
  { id: 'sesame', label: 'Graines de sésame', emoji: '✨', description: 'Et produits à base de graines de sésame' },
  { id: 'sulfites', label: 'Anhydride sulfureux', emoji: '🍷', description: 'Sulfites > 10mg/kg ou 10mg/l' },
  { id: 'lupin', label: 'Lupin', emoji: '🌼', description: 'Et produits à base de lupin' },
  { id: 'mollusques', label: 'Mollusques', emoji: '🦪', description: 'Et produits à base de mollusques' },
]
